name: go.yml
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]
        redis-version: [6, 7]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go mod tidy
        run: go mod tidy

      - name: Test driver database
        working-directory: ./driver/database
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Start redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Test driver redis
        working-directory: ./driver/redis
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Test driver memory
        working-directory: ./driver/memory
        run: |
          go mod tidy
          go test -v -coverprofile=coverage.out ./...

      - name: Upload database coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/database/coverage.out
          fail_ci_if_error: true
          verbose: true
          flags: database,queue,unittests
          codecov_yml_path: ./.codecov.yml

      - name: Upload redis coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/redis/coverage.out
          fail_ci_if_error: true
          verbose: true
          flags: redis,queue,unittests
          codecov_yml_path: ./.codecov.yml

      - name: Upload memory coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./driver/memory/coverage.out
          fail_ci_if_error: true
          verbose: true
          flags: memory,unittests,queue
          codecov_yml_path: ./.codecov.yml
